# Generated by Django 6.1 on 2026-09-27 23:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cuentas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetricItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starts_on', models.DateField()),
                ('ends_on', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('closed', 'Closed')], default='draft', max_length=6)),
            ],
            options={
                'ordering': ['starts_on'],
                'constraints': [models.CheckConstraint(condition=models.Q(('starts_on__lte', models.F('ends_on'))), name='indicator_period_dates_ordered')],
            },
        ),
        migrations.CreateModel(
            name='StaffTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('weight_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('legacy_progress', models.DecimalField(blank=True, decimal_places=2, help_text='Provisional imported progress; not evidence-verified.', max_digits=12, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='targets', to='indicadores.metricitem')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='targets', to='indicadores.period')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='targets', to='cuentas.staffprofile')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('staff', 'period', 'item'), name='unique_staff_period_item'), models.CheckConstraint(condition=models.Q(('goal__gt', 0)), name='target_goal_positive'), models.CheckConstraint(condition=models.Q(('weight_percent__gte', 0), ('weight_percent__lte', 100)), name='target_weight_range'), models.CheckConstraint(condition=models.Q(('legacy_progress__isnull', True), ('legacy_progress__gte', 0), _connector='OR'), name='target_legacy_progress_nonnegative')],
            },
        ),
    ]
