# Generated by Django 6.1 on 2026-09-28 00:15

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cuentas', '0001_initial'),
        ('organizacion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Commitment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(blank=True, max_length=255)),
                ('requester', models.CharField(blank=True, max_length=255)),
                ('territory_label', models.CharField(blank=True, max_length=255)),
                ('support_area', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('registered_on', models.DateField(default=datetime.date.today)),
                ('due_on', models.DateField()),
                ('status', models.CharField(choices=[('Ingresado', 'Ingresado'), ('Pendiente', 'Pendiente'), ('En proceso', 'En proceso'), ('Realizado', 'Realizado')], default='Ingresado', max_length=20)),
                ('note', models.TextField(blank=True)),
                ('delegation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commitments', to='organizacion.delegation')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commitments', to='cuentas.staffprofile')),
            ],
            options={
                'ordering': ['due_on', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CommitmentEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField()),
                ('previous_status', models.CharField(blank=True, choices=[('Ingresado', 'Ingresado'), ('Pendiente', 'Pendiente'), ('En proceso', 'En proceso'), ('Realizado', 'Realizado')], max_length=20, null=True)),
                ('next_status', models.CharField(choices=[('Ingresado', 'Ingresado'), ('Pendiente', 'Pendiente'), ('En proceso', 'En proceso'), ('Realizado', 'Realizado')], max_length=20)),
                ('occurred_on', models.DateField(default=datetime.date.today)),
                ('occurred_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.TextField(blank=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='commitment_events', to=settings.AUTH_USER_MODEL)),
                ('commitment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='agenda.commitment')),
            ],
            options={
                'ordering': ['sequence'],
            },
        ),
        migrations.AddIndex(
            model_name='commitment',
            index=models.Index(fields=['delegation', 'status', 'due_on'], name='agenda_com_del_st_due_idx'),
        ),
        migrations.AddConstraint(
            model_name='commitmentevent',
            constraint=models.UniqueConstraint(fields=('commitment', 'sequence'), name='unique_commitment_event_sequence'),
        ),
    ]
